# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
arr=np.random.random((3,3,3))
# Using random function 
print(arr)



[[[0.35611576 0.28958589 0.78234458]
  [0.69673536 0.35709993 0.93076391]
  [0.54602866 0.18215665 0.05806634]]

 [[0.10948038 0.46629149 0.46097914]
  [0.22258675 0.83982445 0.92198576]
  [0.59918309 0.80057214 0.00705159]]

 [[0.17308178 0.70384401 0.95854568]
  [0.9012884  0.85494016 0.69928457]
  [0.97981509 0.55076468 0.39880523]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
# Create a 5x5 zero matrix using numpy zeros()
arr=np.zeros((5,5), dtype=int)
# print matrix
print(arr)

# using arnage()
arr1=arr+np.arange(5)
#print(arr1)
#using diag() function to print required matrix:

arr1=np.diag(1+np.arange(4), k=-1)
print("Printing required Matrix:::::" ,  '\n' , arr1 )

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Printing required Matrix::::: 
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
arr=np.zeros((8,8), dtype=int)
print("Original Matrix::", "\n" ,arr)
# using slice to make checkerboard pattern:

#Slice from 1st index row till 1+2+2… and fill all columns with 1 starting from 0th to 0+2+2… and so on.
arr[1::2, ::2]=1
#Slice from 0th row till 0+2+2… and fill all columns with 1 starting from 1 to 1+2+2+…..and so on.
arr[::2, 1::2]=1

print("Printing matrix with checkerboard pattern::" , "\n", arr)

Original Matrix:: 
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
Printing matrix with checkerboard pattern:: 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
arr= np.random.random((5,5))
print("Original Array:")
print(arr)

# Normarization of a matrix means scaling in some range like (0,1). So we find max and min value and create a ratio as below.
arr_max= arr.max()
arr_min = arr.min()
arr = (arr - arr_min)/(arr_max - arr_min)
print("After normalization:")
print(arr)

Original Array:
[[0.81705429 0.6834464  0.78503866 0.71682633 0.67202077]
 [0.13323972 0.01294982 0.51512327 0.05929346 0.4245247 ]
 [0.66347951 0.53380422 0.69671236 0.55509818 0.41060445]
 [0.43133723 0.29268745 0.63903137 0.75162113 0.04600486]
 [0.99179809 0.35684116 0.21621821 0.74220807 0.38684138]]
After normalization:
[[0.8214802  0.6849852  0.78877275 0.71908643 0.67331268]
 [0.12288922 0.         0.51302481 0.04734507 0.42046852]
 [0.66458685 0.53210944 0.69853783 0.55386354 0.40624746]
 [0.42742826 0.28578242 0.63961042 0.75463311 0.03376932]
 [1.         0.35132242 0.20766078 0.74501665 0.38197091]]


# 5.  How to find common values between two arrays?

In [5]:

array1 = np.array([2,4,6,8,10])
print("Array1: ",array1)
array2 = np.array([9,5,7,2,4,4,6])
print("Array2: ",array2)


# use intrersect1d() of numpy to find common values between two arrays
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 2  4  6  8 10]
Array2:  [9 5 7 2 4 4 6]
Common values between two arrays:
[2 4 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np

# using dattime64 function along with timedelta64() of numpy.

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


In [7]:
# find today's , yesterday's and tommorow's date without using numpy functions.

import datetime 

#using datetime.date and datetime.timedelta

today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-26
Today :  2020-07-27
Tomorrow :  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
A = np.random.random((2,2))
print(A)
B = np.random.random((2,2))
print(B)
# to check random arrays are equal or not, we use numpy allclose(Array1, Array2) function.
x = np.allclose(A,B)
print(x)

[[0.60195294 0.96100032]
 [0.76606411 0.60984863]]
[[0.54439148 0.31386928]
 [0.38310871 0.25647567]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
arr=np.random.random(10)
print("Original Vector is::" ,"\n", "\n", arr)

#using argmax() to find the postion of max value in array. Replacing that with 0.
arr[arr.argmax()]=0
print("\n")

print("Array after replacing max value by 0 is:::", "\n","\n", arr)

Original Vector is:: 
 
 [0.05867443 0.40358295 0.19543298 0.29053001 0.07857878 0.99876441
 0.65944349 0.99515742 0.54021723 0.21725479]


Array after replacing max value by 0 is::: 
 
 [0.05867443 0.40358295 0.19543298 0.29053001 0.07857878 0.
 0.65944349 0.99515742 0.54021723 0.21725479]


# 9. How to print all the values of an array?

In [10]:
import numpy as np
x=np.arange(1001)
print(x)
np.set_printoptions(threshold=np.inf)
print(x)

[   0    1    2 ...  998  999 1000]
[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189 

# 10.Subtract the mean of each row of a matrix

In [11]:
import numpy as np
print("Original matrix:\n")
x = np.random.random((3,3))
print("\nSubtract the mean of each row of the said matrix:\n")
y = x - x.mean(axis=1, keepdims=True)  # using mean()
print(y)

Original matrix:


Subtract the mean of each row of the said matrix:

[[ 0.1289467  -0.05834192 -0.07060478]
 [ 0.16563748 -0.22582727  0.06018979]
 [ 0.18260299 -0.01786073 -0.16474226]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)

# using bincount()
Z += np.bincount(I, minlength=len(Z))
print( "Output Array:", Z)

Output Array: [4. 4. 3. 2. 4. 1. 3. 3. 3. 3.]


# 12.How to get the diagonal of a dot product?

In [13]:
import numpy as np

A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print(A)
print(B)
print("====einsum====")
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
X=np.einsum('i,i', A, B)    # np.inner(A, B)
print(X)
X=np.einsum('i,j->ij', A, B)    # np.outer(A, B)
print(X)

[0 7 3 1 2 0 6 4 4 4]
[2 3 1 8 9 7 1 3 8 2]
====einsum====
108
[[ 0  0  0  0  0  0  0  0  0  0]
 [14 21  7 56 63 49  7 21 56 14]
 [ 6  9  3 24 27 21  3  9 24  6]
 [ 2  3  1  8  9  7  1  3  8  2]
 [ 4  6  2 16 18 14  2  6 16  4]
 [ 0  0  0  0  0  0  0  0  0  0]
 [12 18  6 48 54 42  6 18 48 12]
 [ 8 12  4 32 36 28  4 12 32  8]
 [ 8 12  4 32 36 28  4 12 32  8]
 [ 8 12  4 32 36 28  4 12 32  8]]


In [ ]:
# We can simply take two arrays to understand this.
import numpy as np

A=np.array([2,3,4])
B=np.array([1,2,3])
print(A)
print(B)
print("====einsum====")  # using einsum() of numpy to calcualte scalar or doct product.
np.einsum('i->', A)  
print(np.einsum('i->', A))  # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
X=np.einsum('i,i', A, B)    # np.inner(A, B) ie dot product of two vectors.
print(X)


# 13.How to find the most frequent value in an array?

In [14]:
# create a random array of size 30
arr=np.random.randint(0,10,30)
print("Original Array with 30 random elements:::", "\n" ,arr)
#Using bincount() with argmax function to find the mode/maxm occurance of an element
arr=np.bincount(arr).argmax()
print("Most frequent value in array is:::", arr)

Original Array with 30 random elements::: 
 [7 8 2 4 7 0 4 0 6 8 5 2 1 4 3 8 3 4 1 6 4 3 7 7 5 3 1 0 5 4]
Most frequent value in array is::: 4


# 14.How to get the n largest values of an array

In [17]:
import numpy as np

x = np.random.randint(0,100,20)
print("Original array:")
print(x)
# using partition() function of numpy to find out n largest values.


print("Enter the number of greatest values to be found in array")
n=int(input())   # taking input from user
x=np.partition(x,-n)  # partition at index at the number user input
print("Array after partition at index -n is" ,"\n", x)

x=np.partition(x,-n)[-n:]  # finding n number of greatest values( in ascending order) as input by user.


print("Array with n largest values:" ,"\n", x)


Original array:
[ 6 25 31  9 68 96 94 32 95 81 57  7  7 33  9 46 83 47  7 39]
Enter the number of greatest values to be found in array
5
Array after partition at index -n is 
 [ 7  6 31  9  7  9 33 32  7 25 39 47 46 57 68 81 83 94 95 96]
Array with n largest values: 
 [81 83 94 95 96]


# 15.How to create a record array from a regular array?

In [ ]:
# Create a Record Array from a regular array. 
#Record Array construct an ndarray that allows field access using attributes.
# Record arrays allow the fields to be accessed as members of the array, using arr.x and arr.y.

# Creating an array with 2 fields a as float and b as int
import numpy as np

input_arr = np.array([(5.0, 2), (3.0, 4)], 
         dtype =[('a', float), ('b', int)]) 
print("Input array : ", input_arr)

# convert it to a record array, using arr.view(np.recarray) 
record_arr = input_arr.view(np.recarray) 
print("Record array of float: ", record_arr.a) 
print("Record array of int: ", record_arr.b) 
  
# applying recarray.all methods to float record array 
output_arr = np.recarray.all(record_arr.a) 
print ("Output array: ", output_arr)  
  
# applying recarray.all methods to int record array 
output_arr = np.recarray.all(record_arr.b) 

